-- +migrate Up
CREATE SCHEMA AUTH;

CREATE TABLE AUTH.CLIENT
(
    id                        VARCHAR(255) NOT NULL,
    SECRET                    VARCHAR(255),
    HASHED_SECRET             VARCHAR(255),
    HASHED_REGISTRATION_TOKEN VARCHAR(255),
    REGISTRATION_TYPE         VARCHAR(18),
    EXPIRES_AT                INT,
    CLIENT_META_INFO          JSONB,
    CONSTRAINT CLIENT_PK PRIMARY KEY (id)
);

CREATE TABLE AUTH.AUTHN_SESSION
(
    id                 VARCHAR(255) NOT NULL,
    SUBJECT            VARCHAR(255) NOT NULL,
    CLIENT_ID          VARCHAR(255) NOT NULL,
    PUSHED_AUTH_REQ_ID VARCHAR(255),
    CALLBACK_ID        VARCHAR(255),
    CIBA_AUTH_ID       VARCHAR(255),
    AUTH_CODE          VARCHAR(255),
    VALUE              JSONB,
    CONSTRAINT AUTHN_SESSION_PK PRIMARY KEY (id)
);

CREATE INDEX AUTHN_SESSION_CALLBACK_ID_IX ON AUTH.AUTHN_SESSION (CALLBACK_ID);

CREATE INDEX AUTHN_SESSION_AUTH_CODE_IX ON AUTH.AUTHN_SESSION (AUTH_CODE);

CREATE INDEX AUTHN_SESSION_PUSHED_AUTH_REQ_ID_IX ON AUTH.AUTHN_SESSION (PUSHED_AUTH_REQ_ID);

CREATE INDEX AUTHN_SESSION_CIBA_AUTH_ID_IX ON AUTH.AUTHN_SESSION (CIBA_AUTH_ID);

CREATE TABLE AUTH.GRANT_SESSION
(
    id                              VARCHAR(255) NOT NULL,
    TOKEN_ID                        VARCHAR(255) NOT NULL,
    REFRESH_TOKEN_ID                VARCHAR(255),
    LAST_TOKEN_EXPIRES_AT_TIMESTAMP INT,
    CREATED_AT_TIMESTAMP            INT,
    EXPIRES_AT_TIMESTAMP            INT,
    AUTH_CODE                       VARCHAR(255),
    GRANT_INFO                      JSONB,
    CONSTRAINT GRANT_SESSION_PK PRIMARY KEY (id)
);

CREATE INDEX GRANT_SESSION_TOKEN_ID_IX ON AUTH.GRANT_SESSION (TOKEN_ID);

CREATE INDEX GRANT_SESSION_REFRESH_TOKEN_ID_IX ON AUTH.GRANT_SESSION (REFRESH_TOKEN_ID);

CREATE INDEX GRANT_SESSION_AUTH_CODE_IX ON AUTH.GRANT_SESSION (AUTH_CODE);

CREATE TABLE AUTH.SESSION_STORE
(
    id VARCHAR(36) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    AUTH_TIME INT,
    CONSTRAINT SESSION_STORE_PK PRIMARY KEY (id)
);

-- +migrate Down
DROP TABLE AUTH.SESSION_STORE;

DROP INDEX AUTH.GRANT_SESSION_AUTH_CODE_IX;

DROP INDEX AUTH.GRANT_SESSION_REFRESH_TOKEN_ID_IX;

DROP INDEX AUTH.GRANT_SESSION_TOKEN_ID_IX;

DROP TABLE AUTH.GRANT_SESSION;

DROP INDEX AUTH.AUTHN_SESSION_CIBA_AUTH_ID_IX;

DROP INDEX AUTH.AUTHN_SESSION_PUSHED_AUTH_REQ_ID_IX;

DROP INDEX AUTH.AUTHN_SESSION_AUTH_CODE_IX;

DROP INDEX AUTH.AUTHN_SESSION_CALLBACK_ID_IX;

DROP TABLE AUTH.AUTHN_SESSION;

DROP TABLE AUTH.CLIENT;

DROP SCHEMA AUTH;